package org.example.packing.application.strategy;

import org.example.packing.domain.model.PlacedPackage;
import org.example.packing.domain.model.Position;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Generates extreme points (candidate placement positions) for the
 * Extreme-Point-Based 3D Bin Packing heuristic
 * (Crainic, Perboli, Tadei — "Extreme Point-Based Heuristics for Three-Dimensional
 * Bin Packing", INFORMS Journal on Computing, 2008).
 * <p>
 * When a package is placed, this generator yields up to three new extreme points:
 * one to its right (along X), one behind it (along Y), and one on top (along Z).
 * <p>
 * This is a simplified projection-free variant — sufficient for production use cases
 * with reasonable item counts (≲ 10⁴) and dramatically simpler than the full
 * projection-based algorithm.
 */
final class ExtremePointGenerator {

	/**
	 * Returns the candidate extreme points generated by placing {@code placed}.
	 * The initial origin is always implicitly available and managed by the caller.
	 */
	Set<Position> pointsAfterPlacing(final PlacedPackage placed) {
		final Set<Position> points = LinkedHashSet.newLinkedHashSet(3);
		// Right of the package (along the length axis)
		points.add(new Position(placed.endX(), placed.position().y(), placed.position().z()));
		// Behind the package (along the width axis)
		points.add(new Position(placed.position().x(), placed.endY(), placed.position().z()));
		// On top of the package (along the height axis)
		points.add(new Position(placed.position().x(), placed.position().y(), placed.endZ()));
		return points;
	}
}
